class WrapperRule:
    def to_python(self, value, *, absent: bool = ...): ...
    def to_proto(self, value): ...

class DoubleValueRule(WrapperRule): ...
class FloatValueRule(WrapperRule): ...
class Int64ValueRule(WrapperRule): ...
class UInt64ValueRule(WrapperRule): ...
class Int32ValueRule(WrapperRule): ...
class UInt32ValueRule(WrapperRule): ...
class BoolValueRule(WrapperRule): ...
class StringValueRule(WrapperRule): ...
class BytesValueRule(WrapperRule): ...
