import datetime

class DatetimeWithNanoseconds(datetime.datetime):
    def __new__(cls, *args, **kw): ...
    def replace(self, *args, **kw): ...
    @property
    def nanosecond(self): ...
    def rfc3339(self): ...
    @classmethod
    def from_rfc3339(cls, stamp): ...
    def timestamp_pb(self): ...
    @classmethod
    def from_timestamp_pb(cls, stamp): ...
