import collections.abc

from proto.utils import cached_property as cached_property

class MapComposite(collections.abc.MutableMapping):
    def __init__(self, sequence, marshal) -> None: ...
    def __contains__(self, key): ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __len__(self): ...
    def __iter__(self): ...
    @property
    def pb(self): ...
